// Code generated by "stringer -linecomment -type=Token,Kind -output=stringers.go"; DO NOT EDIT.

package ohimark

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokUndefined-0]
	_ = x[TokIllegal-1]
	_ = x[TokEOF-2]
	_ = x[TokWord-3]
	_ = x[TokDigits-4]
	_ = x[TokSpace-5]
	_ = x[TokNewline-6]
	_ = x[runBeg-7]
	_ = x[TokHash-8]
	_ = x[TokStar-9]
	_ = x[TokUnderscore-10]
	_ = x[TokTick-11]
	_ = x[TokTilde-12]
	_ = x[TokDash-13]
	_ = x[TokGT-14]
	_ = x[runEnd-15]
	_ = x[TokPlus-16]
	_ = x[TokBang-17]
	_ = x[TokLT-18]
	_ = x[TokBracketL-19]
	_ = x[TokBracketR-20]
	_ = x[TokParenL-21]
	_ = x[TokParenR-22]
	_ = x[TokDot-23]
	_ = x[TokEscape-24]
	_ = x[TokEntity-25]
}

const _Token_name = "undefinedillegalEOF<word><digits><space><newline>runBeg#*_`~->runEnd+!<[]().<escape><entity>"

var _Token_index = [...]uint8{0, 9, 16, 19, 25, 33, 40, 49, 55, 56, 57, 58, 59, 60, 61, 62, 68, 69, 70, 71, 72, 73, 74, 75, 76, 84, 92}

func (i Token) String() string {
	if i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindUndefined-0]
	_ = x[KindDocument-1]
	_ = x[containerBeg-2]
	_ = x[KindBlockQuote-3]
	_ = x[KindList-4]
	_ = x[KindItem-5]
	_ = x[containerEnd-6]
	_ = x[leafBeg-7]
	_ = x[KindParagraph-8]
	_ = x[KindHeading-9]
	_ = x[KindCodeBlock-10]
	_ = x[KindThematicBreak-11]
	_ = x[leafEnd-12]
	_ = x[inlineBeg-13]
	_ = x[KindEmph-14]
	_ = x[KindStrong-15]
	_ = x[KindLink-16]
	_ = x[KindImage-17]
	_ = x[KindCodeSpan-18]
	_ = x[KindText-19]
	_ = x[KindEscape-20]
	_ = x[KindEntity-21]
	_ = x[KindAutolink-22]
	_ = x[KindSoftBreak-23]
	_ = x[KindHardBreak-24]
	_ = x[inlineEnd-25]
	_ = x[KindInfo-26]
	_ = x[KindDest-27]
	_ = x[KindTitle-28]
	_ = x[KindRaw-29]
}

const _Kind_name = "undefineddocumentcontainerBegblockquotelistitemcontainerEndleafBegparagraphheadingcodeblockthematicbreakleafEndinlineBegemphstronglinkimagecodespantextescapeentityautolinksoftbreakhardbreakinlineEndinfodesttitleraw"

var _Kind_index = [...]uint8{0, 9, 17, 29, 39, 43, 47, 59, 66, 75, 82, 91, 104, 111, 120, 124, 130, 134, 139, 147, 151, 157, 163, 171, 180, 189, 198, 202, 206, 211, 214}

func (i Kind) String() string {
	if i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
